# Nord theme
gui:
  theme:
    activeBorderColor:
      - '#88C0D0'
      - bold
    inactiveBorderColor:
      - '#4C566A'
    optionsTextColor:
      - '#81A1C1'
    selectedLineBgColor:
      - '#3B4252'
    cherryPickedCommitBgColor:
      - '#434C5E'
    cherryPickedCommitFgColor:
      - '#88C0D0'
    unstagedChangesColor:
      - '#BF616A'
    defaultFgColor:
      - '#D8DEE9'
    searchingActiveBorderColor:
      - '#EBCB8B'

  authorColors:
    '*': '#A3BE8C'

# Catpuccin Mocha theme
# gui:
#   theme:
#     activeBorderColor:
#     - '#cba6f7'
#     - bold
#     inactiveBorderColor:
#       - '#a6adc8'
#     optionsTextColor:
#       - '#89b4fa'
#     selectedLineBgColor:
#       - '#313244'
#     cherryPickedCommitBgColor:
#       - '#45475a'
#     cherryPickedCommitFgColor:
#       - '#cba6f7'
#     unstagedChangesColor:
#       - '#f38ba8'
#     defaultFgColor:
#       - '#cdd6f4'
#     searchingActiveBorderColor:
#       - '#f9e2af'

#   authorColors:
#     '*': '#b4befe'